version: "2.4"
services:
  electrs:
    container_name: ${COMPOSE_PROJECT_NAME}_electrs
    image: stk-sr/electrs:${ELECTRS_VERSION}-alpine
    restart: unless-stopped
    command: [
      'electrs',
      '-vv',
      '--timestamp',
      '--network=regtest',
      '--daemon-p2p-addr=bitcoin:${BITCOIN_PORT}',
      '--daemon-rpc-addr=bitcoin:${BITCOIN_RPC_PORT}',
      '--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT}',
      '--db-dir=/home/electrs/db'
    ]
    ports:
      - "127.0.0.1:${ELECTRS_PORT}:${ELECTRS_PORT}"
    depends_on:
      - bitcoin
    networks:
      srnet:
        aliases:
          - ${ELECTRS_HOST}