version: "2.4"
volumes:
  electrs_data:
  storm1_data:
  storm2_data:

services:
  electrs:
    container_name: electrs
    image: sr/electrs:latest
    build:
      context: ./electrs/
    restart: unless-stopped
    command:
      [
        "electrs",
        "--timestamp",
        "--network=regtest",
        "--db-dir=/home/electrs/db",
        "--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT}",
        "--daemon-p2p-addr=node1:${BITCOIN_PORT}",
        "--daemon-rpc-addr=node1:${BITCOIN_RPC_PORT}",
      ]
    volumes:
      - electrs_data:/home/electrs
    depends_on:
      - node1
    ports:
      - ${ELECTRS_PORT}:${ELECTRS_PORT}
    networks:
      sr_network:
        ipv4_address: 172.20.0.22
        aliases:
          - ${ELECTRS_HOST}

  storm1:
    container_name: storm1
    image: sr/storm:latest
    build:
      context: ./storm-node/
    command:
      [
        "-vvvv",
        "--data-dir=${STORM_DATA_DIR}",
        "--store-endpoint=${STORE_DATA_DIR}",
        "--msg=${LNP_IP_1}:${LNP_RPC_PORT}",
        "--chat",
        "--downpour",
      ]
    depends_on:
      - lnp1
      - store1
    volumes:
      - storm1_data:/var/lib/storm
      - ./shared/storm-stored:/var/lib/store 
    networks:
      sr_network:
        ipv4_address: 172.20.0.20